name: Release
on:
  workflow_dispatch:
    inputs:
      level:
        type: choice
        required: true
        description: "bump to [major|minor|patch]"
        options:
          - "major"
          - "minor"
          - "patch"
        default: "minor"
jobs:
  release:
    uses: tmknom/github-actions-workflows/.github/workflows/release.yml@v0
    with:
      level: ${{ inputs.level }}
